# NumPy 

In [1]:
import numpy as np

Create a random vector of size 10 and sort it

In [2]:
np.sort(np.random.rand(10))

array([0.0284682 , 0.05454504, 0.07208046, 0.24748131, 0.52623194,
       0.62953255, 0.67866333, 0.78223255, 0.87675443, 0.92600755])

Create a random vector of size 20 and find the mean value

In [3]:
np.random.rand(20).mean()

0.44429700460295657

Create a 2x2x2 array with random values

In [4]:
np.random.rand(2, 2, 2)

array([[[0.50360809, 0.85925371],
        [0.36677642, 0.07946938]],

       [[0.25034666, 0.5325324 ],
        [0.295687  , 0.50957353]]])

Create a 4x4 matrix with values ranging from 0 to 9

In [5]:
np.random.randint(low=0, high=9, size=(4, 4))

array([[0, 3, 4, 8],
       [0, 8, 4, 2],
       [3, 3, 1, 0],
       [5, 1, 7, 2]])

Find common values between two arrays

In [6]:
a = np.random.randint(low=0, high=9, size=10)
b = np.random.randint(low=0, high=9, size=10)
np.intersect1d(a, b)

array([0, 1, 2, 5, 7])

Find the nearest value from a given value in an array

In [7]:
a = np.random.random(10) * 100
value = 14.4
a[np.abs(a - value).argmin()]

8.322741226533036